### ISSUE TITLE
[feature request] double meters / no return power

### ISSUE THREAD

**Issue by Dradallor** [koktaildotcom/com.p1.smartmeter#2]
Hi Guys,

Sorry for the separate topics, but wanted to keep it clean.
An additional feature that could be considered for this is to give people to option to enable/disable the Electricity returned option and be able to show the Double meters (for the people with a Day/Night cycle) seems the code is finding both cycles but no option to show them separately.

Regards,
Mike

**Comment by koktaildotcom** [comment]
Nothing to sorry about, its another topic.  :)
This is done as intended because otherwise the sensor contains to much sensors.
We can split them up in 2 devices, one for electricity and one for gas?

What do you have a proposal?

**Comment by Dradallor** [comment]
That does indeed make sense, a lot of information on the screen would be painful.
Splitting Power and Gas into two devices would be a good bet I think.

**Comment by koktaildotcom** [comment]
I'll look into that

**Comment by pro-sumer** [comment]
Do all P1 smart meters support 2 tariffs? (Never 1?)

I experimented for my own situation (2 tarrifs). After splitting up energy and gas into two different devices I can fit 8 energy sensors on an iPhone X screen, which is exactly enough.

@koktaildotcom Are you still planning to add this? (When?)

I kind of like the extra capabilities/sensors and device split I "implemented", but I'm new to Homey and I'm not sure my code is good enough for a Pull Request. For example: I lost all my historic data (not much since I'm new) when experimenting; how would one prevent this for other users?

**Comment by koktaildotcom** [comment]
I think capabilities can't be enabled/disabled in Homey. 

I think there should be multiple drivers for each different model. In the installation process there should be questions like:

1. How many meters electricity delivery do you have?
1. How many meters electricity redelivery do you have?
1. Do you have a gas meter do you have? 

Based on that you can add a specific device with either:
1. elec 1x
1. elec 2x
1. elec 1x + 1x
1. elec 2x + 2x
1. gas + elec 1x
1. gas + elec 2x
1. gas + elec 1x + 1x
1. gas + elec 2x + 2x

Because this project is in my free time i don't think i'll implement this feature anytime soon.
You can provide a pull request for features, then i'll look at it and merge it if its an upgrade.

**Comment by pro-sumer** [comment]
Ouch; seems complicated (and there is at least 1 more variation point: the gas meter interval)

Maybe I should just side load my private fork, which only supports my particular case:

* 2 drivers that each implement 1 device
  * Electricity (double tariff)
  * Gas (update every 5 minutes instead of every hour)

**Comment by koktaildotcom** [comment]
This is implemented by @hfaas. Many thanks for your contribution!
